# Database
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Port
server.port=${PORT:8081}
# Upload dir
app.upload.dir=/tmp/uploads
# Gemini
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=${GEMINI_API_URL}
# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=https://web-production-e31ac.up.railway.app/login/oauth2/code/google
server.forward-headers-strategy=native
# Mail
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=${MAIL_USERNAME}
# Matikan devtools di production
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false
# Percepat JPA initialization
spring.jpa.open-in-view=false
# Logging
logging.level.root=INFO
logging.level.com.docmonitor=DEBUG
logging.level.org.springframework=INFO
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never