
# APPLICATION CONFIG - Document Monitoring System

spring.application.name=document-monitoring

# Server
server.port=8081

# Static Resources
spring.web.resources.static-locations=classpath:/static/
spring.web.resources.cache.period=0
spring.web.resources.cache.cachecontrol.max-age=0
spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.no-store=true


# DATABASE - PostgreSQL (ACTIVE)
spring.datasource.url=jdbc:postgresql://localhost:5432/document_monitoring_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


# FILE UPLOAD
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Path penyimpanan file dokumen
app.upload.dir=./uploads/documents


# GOOGLE GEMINI API
gemini.api.key=YAIzaSyBaBJ_dvgbDVhixjzz0kT8c1AUU-tjKvzQ
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent


# EMAIL - SMTP (Gmail)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=a9098de44e79de
spring.mail.password=579326d57bace3
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
app.mail.from=noreply@docmonitor.local
app.mail.from-name=DocMonitor Dev Team

# Base URL untuk link di email invite (sesuaikan dengan server)
app.base-url=http://localhost:8081


# SCHEDULER (Cron Job)
app.scheduler.cron=0 0 8 * * *
app.scheduler.warning-days=30


# SECURITY
app.admin.default-email=admin@docmonitor.com
app.admin.default-password=Admin@123


# THYMELEAF
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# thred pool untuk @Async (jika digunakan)
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
spring.task.execution.pool.queue-capacity=25
spring.task.execution.thread-name-prefix="DocMonitor-Async-"